### ISSUE TITLE
Fix .gitignore for sonarqube config

### ISSUE THREAD

**Issue by JuanDGiraldoM** [bancolombia/scaffold-clean-architecture-ex#29]
When I generate sonarqube config, it doesn't omit all files

<img width="518" alt="image" src="https://github.com/bancolombia/scaffold-clean-architecture-ex/assets/25773228/ce8cf412-148c-4f49-bb74-1db5e49783f6">

**Comment by juancgalvis** [comment]
Default location of this reports changed and ignored, file generic_test_execution_sonarqube.xml moved when generated using new mix ca.release task
